version: '3.1'

services:
    db:
        image: mariadb
        restart: always
        env_file:
            .env
        networks:
            - compose-networks
        ports:
            - "3307:3306"
        expose:
            - 3307
        volumes:
            - ./dbdata:/var/lib/mysql/data

    node:
        build: .
        restart: always
        ports:
            - "3001:3001"
        depends_on:
            - db
        networks: 
            - compose-networks

networks:
    compose-networks:
